version: '3.8'

services:
  nginx-dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - aegis-dev

  aegis-dev:
    build:
      context: ./src
      dockerfile: Dockerfile-dev
    ports:
      - "5666:5666"
    environment:
      - PORT=5666