version: '3.8'

services:
  aegis-dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Map host port 5000 to container port 80
    # volumes:
      # Optional: Mount HTML files for development (uncomment for live reload)
      # - ./login-success.html:/usr/share/nginx/html/login-success.html:ro
      # - ./login-error.html:/usr/share/nginx/html/login-error.html:ro