version: '3.8'

services:
  aegis-dev-pages:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aegis-dev-pages
    ports:
      - "5000:80"  # Map host port 5000 to container port 80
    volumes:
      # Optional: Mount HTML files for development (uncomment for live reload)
      # - ./login-success.html:/usr/share/nginx/html/login-success.html:ro
      # - ./login-error.html:/usr/share/nginx/html/login-error.html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aegis-dev-network

networks:
  aegis-dev-network:
    driver: bridge 